// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hdhnxjjnkordeqfjecjk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhkaG54ampua29yZGVxZmplY2prIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjY5OTYzNTMsImV4cCI6MjA4MjU3MjM1M30.cdCmE0EcilgqmdssjbMaWCBxbG-WD1TCs9d4W6VtY0Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});